import os
import re
import time
import logging
import ipaddress
from packaging.version import Version
from retry import retry

from hwinfo.run_cmd import run_cmd

SYSTEMD_UNITS_PATH = "/lib/systemd/system"

CONFIGURE_SRIOV_TEMPLATE = """
### generated by ClusterUtils plugin ###
[Unit]
Description=Open sriov on {iface_name}
Before=network-pre.target

[Service]
Type=oneshot
ExecStart=/bin/bash -c 'echo {num_vfs} > /sys/class/net/{iface_name}/device/sriov_numvfs && sleep 2'
StandardOutput=journal

[Install]
WantedBy=multi-user.target
"""


def get_os_release_info():
    """Parses the /etc/os-release file and returns a dictionary containing all information.

    Returns:
        A dictionary containing OS release information, or an empty dictionary if the file is not found or unreadable.
    """
    try:
        with open("/etc/os-release") as f:
            os_release_info = dict(line.strip().split("=") for line in f)
    except (FileNotFoundError, PermissionError):
        os_release_info = {}
    return os_release_info


def ifaces_network_manager_controlled() -> bool:
    os_release_info = get_os_release_info()
    version_id = Version(os_release_info["VERSION_ID"])
    if is_rhel_family() and version_id > Version("8"):
        return True
    if os_release_info["ID"] == "ubuntu" and version_id >= Version("20.04"):
        return True
    else:
        return False


def is_rhel_family():
    os_release_info = get_os_release_info()
    return os_release_info["ID"] in ["centos", "rhel", "almalinux", "rocky"]


class NetworkInterface(object):
    def __init__(self, name):
        self._name = name
        self._type = "unknown"
        self._numa_node_id = None
        self._real_device_path = run_cmd("realpath /sys/class/net/{}/device".format(name))
        self._is_virtio = "virtio" in self._real_device_path
        self._type = self._get_iface_type()

    @property
    def name(self):
        return self._name

    @property
    def mac_address(self):
        return self._get_mac_address()

    @property
    def is_virtio(self):
        return self._is_virtio

    @property
    def pci_dev(self):
        """returns the pci id of a device in the following format: 0000:00:04.0"""
        if self.is_pci_device:
            return os.path.basename(os.path.dirname(self._real_device_path)).strip() if self.is_virtio else os.path.basename(self._real_device_path).strip()
        return ""

    @property
    def ipv4(self):
        line = run_cmd(f"ip -o -f inet addr show {self.name}")
        return ipaddress.IPv4Interface(line.split()[3]) if line else None

    @property
    def ipv4_address(self):
        """return the ip v4 address or empty string"""
        ipv4iface = self.ipv4
        return str(ipv4iface.ip) if ipv4iface else ""

    @property
    def ipv6(self):
        line = run_cmd(f"ip -o -f inet6 addr show {self.name}")
        return ipaddress.IPv6Interface(line.split()[3]) if line else None

    @property
    def ipv6_address(self):
        """return the ip v6 address or empty string"""
        ipv6iface = self.ipv6
        return str(ipv6iface.ip) if ipv6iface else ""

    @property
    def link_detected(self):
        self.install_ethtool()
        try:
            value = run_cmd(f"ethtool {self.name} | grep 'Link detected'").strip().split(":")[1].strip()
        except Exception as ex:
            logging.error("failed to get link status for iface: %s. error: %s", self.name, str(ex))
            return False
        return True if value.lower() == "yes" else False

    @property
    def is_pci_device(self):
        return self._real_device_path.startswith("/sys/devices/pci") and not "usb" in self._real_device_path

    @property
    def is_virtual_function(self):
        if self.is_pci_device:
            return "virtual" in run_cmd('lspci -s {}'.format(self.pci_dev)).lower()
        return "unknown"

    @property
    def subsystem(self):
        if not self.is_pci_device:
            return ""
        cmd = "lspci -vvD -s {}".format(self.pci_dev)
        output = run_cmd(cmd)
        for line in output.split("\n"):
            splitted = [item.strip() for item in line.strip().split(":")]
            if splitted[0].lower() == 'subsystem':
                return splitted[1]
        return ""

    @property
    def ethernet_controller(self):
        if not self.is_pci_device:
            return ""
        cmd = 'lspci -vvD -s {} | grep -E "Network controller|Ethernet controller"'.format(self.pci_dev)
        output = run_cmd(cmd)
        if "controller:" in output:
            return output.split("controller:")[1]
        return ""

    @property
    def iface_type(self):
        return self._type

    @property
    def numa_node_id(self):
        # aws vms can override this value from the outside cause all nics are enumerated as -1
        # numa node id on AWS
        if self._numa_node_id != None:
            return self._numa_node_id
        # in virtio ifaces we dont have this file for some reason so we handle it here
        if self.is_virtio:
            return 0
        numa_path = f'cat /sys/class/net/{self.name}/device/numa_node'
        if not os.path.exists(numa_path):
            return 0
        numa_id = int(run_cmd(numa_path).strip())
        # if we have only one numa the value will be -1
        return numa_id if numa_id >= 0 else 0

    @property
    def mtu(self):
        return self._mtu

    def install_ethtool(self):
        try:
            run_cmd("which ethtool")
        except:
            logging.info("ethtool not found, installing")
            if is_rhel_family():
                run_cmd("yum install ethtool")
            else:
                run_cmd("apt install ethtool")

    def set_mtu(self, mtu):
        self._mtu = mtu

    def set_numa_node_id(self, numa_id):
        self._numa_node_id = numa_id

    def flush(self):
        run_cmd("ip addr flush {}".format(self.name))

    def set_mac_address(self, mac):
        logging.info("iface: %s. setting mac address: %s", self._name, mac)
        run_cmd("ip link set address %s dev %s", mac, self._name)

    retry(tries=5, delay=1)
    def _get_mac_address(self):
        try:
            mac = run_cmd("cat /sys/class/net/{}/address".format(self._name)).strip()
            logging.info("detected mac: %s on iface: %s", mac, self._name)
            return mac
        except:
            logging.error("failed to retrieve mac address for iface: %s", self._name)
            return None

    @property
    def kernel_modules(self):
        """return the modules that are associated with this device from lspci"""
        if not self.is_pci_device:
            return ""
        output = run_cmd("lspci -vvD -s {}".format(self.pci_dev))
        for line in output.split("\n"):
            splitted = [item.strip() for item in line.strip().split(":")]
            if splitted[0].lower() == 'kernel modules':
                return splitted[1]
        return ""

    @property
    def is_mellanox(self):
        modules = self.kernel_modules
        if "mlx4_core" in modules or "mlx5_core" in modules:
            return True
        return False

    @property
    def mellanox_version(self):
        modules = self.kernel_modules
        if "mlx4_core" in modules:
            return 4
        if "mlx5_core" in modules:
            return 5

    def _mlx4_wa_configure_gid_manually(self):
        portnum = run_cmd("cat /sys/class/net/%s/dev_port" % self._name).strip()
        output = run_cmd('dmesg | grep MAC | grep "Port %s"' % str(int(portnum) + 1))
        dmesg_mac = output.splitlines()[-1].split(' ')[-1]
        current_mac = self._get_mac_address()
        if dmesg_mac != current_mac:
            logging.info("iface %s: current MAC address is different than dmesg MAC, Changing MAC from %s to %s",
                         self._name, current_mac, dmesg_mac)
        return dmesg_mac

    def _mlx5_wa_configure_gid_manually(self):
        output = run_cmd('dmesg | grep MAC | grep mlx5_core | grep %s' % self.pci_dev)
        dmesg_mac = output.splitlines()[-1].split(' ')[-1]
        current_mac = self._get_mac_address()
        if dmesg_mac != current_mac:
            logging.info("iface %s: current MAC address is different than dmesg MAC, Changing MAC from %s to %s",
                         self._name, current_mac, dmesg_mac)
        return dmesg_mac

    def enable_vfs(self, num_vfs):
        cmd = 'echo %d > /sys/class/net/%s/device/sriov_numvfs' % (num_vfs, self._name)
        logging.info("opening virtual function: %s", cmd)
        run_cmd(cmd)
        time.sleep(2)

    def enable_vfs_persistant(self, num_vfs):
        contents = CONFIGURE_SRIOV_TEMPLATE.format(iface_name=self._name, num_vfs=num_vfs)
        service_name = "{}-sriov.service".format(self._name)
        with open(os.path.join(SYSTEMD_UNITS_PATH, service_name), "w") as f:
            f.write(contents)
        run_cmd("systemctl daemon-reload")
        run_cmd("systemctl enable {}".format(service_name))
        run_cmd("systemctl start {}".format(service_name))

    @property
    def sriov_numvfs_count(self):
        try:
            return int(run_cmd("cat /sys/class/net/{}/device/sriov_numvfs".format(self._name)).strip())
        finally:
            pass
        return 0

    def ip_link_up(self):
        """ iproute2 tool doesn't require the ifcfg-<iface> or interfaces.d/<iface-name> files to be present.
            in case they are not present it will do nothing.
            if one will add an ip address on the device prior to calling "set up"
            the device will be shown and up by the kernel.
            otherwise if we didn't add a config file and we didn't add address
            we will see the device as up but it will not show in 'ip addr' cmd and will
            not get an IP.
        """
        run_cmd("ip link set up dev {}".format(self._name))

    def ip_link_down(self):
        """ iproute2 tool doesn't require the ifcfg-<iface> or interfaces.d/<iface-name> files to be present.
            in case they are not present it will do nothing.
            if one will add an ip address on the device prior to calling "set up"
            the device will be shown and up by the kernel.
            otherwise if we didn't add a config file and we didn't add address
            we will see the device as up but it will not show in 'ip addr' cmd and will
            not get an IP.
        """
        run_cmd("ip link set down dev {}".format(self._name))

    def ifup(self):
        """ ifup require the ifcfg-<iface> or interfaces.d/<iface-name> files to be present.
            in case these files are not present this call will fail.
        """
        cmd = f"ifup {self._name}"

        if ifaces_network_manager_controlled():
            cmd = f"nmcli con up {self._name}"

        run_cmd(cmd)

    @retry(tries=5, delay=1)
    def ifdown(self):
        """ ifdown require the ifcfg-<iface> or interfaces.d/<iface-name> files to be present.
            in case these files are not present this call will fail.
        """
        cmd = f"ifdown {self._name}"

        if ifaces_network_manager_controlled():
            cmd = f"nmcli con down {self._name}"

        run_cmd(cmd)

    def is_up(self):
        output = run_cmd(f"cat /sys/class/net/{self._name}/operstate")
        return "up" == output.strip()

    def is_down(self):
        output = run_cmd(f"cat /sys/class/net/{self._name}/operstate")
        return output.strip().lower() in ("down", "unknown")

    def __repr__(self):
        res = "name: " + self.name
        res += ", numa_node_id: " + str(self.numa_node_id)
        res += ", is_virtio: " + str(self.is_virtio)
        res += ", type: " + str(self._type)
        res += ", mac_address: " + self.mac_address
        res += ", is_pci_device: " + str(self.is_pci_device)
        res += ", ip: " + str(self.ipv4)
        res += ", ipv6: " + str(self.ipv6)
        res += ", link_detected: " + str(self.link_detected)
        if self.is_pci_device:
            res += ", subsystem: " + self.subsystem
            res += ", pci_dev: " + self.pci_dev
            res += ", is_virtual_function: " + str(self.is_virtual_function)
        return res

    def __str__(self):
        res = "name: " + self.name
        res += ", numa_node_id: " + str(self.numa_node_id)
        res += ", is_virtio: " + str(self.is_virtio)
        res += ", type: " + str(self._type)
        res += ", mac_address: " + self.mac_address
        res += ", is_pci_device: " + str(self.is_pci_device)
        res += ", ipv4: " + self.ipv4_address
        res += ", ipv6: " + str(self.ipv6)
        res += ", link_detected: " + str(self.link_detected)
        if self.is_pci_device:
            res += ", subsystem: " + self.subsystem
            res += ", pci_dev: " + self.pci_dev
            res += ", is_virtual_function: " + str(self.is_virtual_function)
        return res

    def _get_iface_type(self) -> str:
        if self._is_mellanox_nic() or \
            self._is_solarflare_nic() or \
            self._is_data_intel_nic():
            return "data"
        return "access"

    def _is_mellanox_nic(self):
        subsystem = self.subsystem
        eth_controller = self.ethernet_controller
        return 'Mellanox Technologies'.lower() in subsystem.lower() or \
                re.search('ConnectX-[456]', subsystem, re.IGNORECASE|re.MULTILINE) or \
                re.search('ConnectX-[456]', eth_controller, re.IGNORECASE|re.MULTILINE)

    def _is_solarflare_nic(self):
        subsystem = self.subsystem.lower() if self.subsystem else ""
        return 'Solarflare Communications'.lower() in subsystem

    def _is_data_intel_nic(self):
        subsystem = self.subsystem.lower() if self.subsystem else ""
        if 'Intel Corporation'.lower() not in subsystem:
            return False

        non_data_intel_nics = [
            'Intel Corporation I350 Gigabit Network Connection',
            'Intel Corporation Gigabit CT Desktop Adapter',
            'Intel Corporation Device 35cf',
            'Intel Corporation Device 35c6',
            'Intel Corporation Ethernet Network Adapter X710-TL',
            'Intel Corporation Ethernet Connection X722 for 1GbE',
            'Intel Corporation Ethernet Network Adapter X710-T2L for OCP 3.0'
        ]
        for nic in non_data_intel_nics:
            if nic.lower() in subsystem:
                return False

        if 'Intel Corporation Ethernet Server Adapter X520-2'.lower() in subsystem:
            return True
            # # In EPYC/QCT the Intel X520-2 NIC is used as access NIC
            # chassis_vendor = self._host.admin.chassis_vendor
            # return 'Quanta Cloud Technology Inc.' not in chassis_vendor

        return True

    def _is_usb_interface(self):
        '''
        if "u" found in the iface name, this a sign that its a usb connection, we dont use that as
        a network device in the lab currently
        https://webhostinggeeks.com/howto/new-naming-scheme-for-the-network-interface-on-rhel-7centos-7/
        :param ifanme: iface name, examle ens01 or enp0s20f0u1u6
        :return: Boolean
        '''
        return 'u' in self._name

    def to_json(self):
        import json
        return json.dumps(self, default=lambda o: o.__dict__, sort_keys=True)

    def assign_ip_persistent(self, ip_address, length="16"):
        """Assigns an IPv4 address to a network interface persistently (if supported by OS).

        Args:
            interface: The name of the network interface (e.g., "eth0", "wlan0").
            ip_address: The IPv4 address in string format (e.g., "192.168.1.10").
            netmask: The netmask in string format (default: "255.255.255.0").

        Raises:
            OSError: If the command fails to execute or encounters errors.
        """
        # Example using ip command (replace with appropriate command for your OS)
        command = f"ip addr add {ip_address}/{length} dev {self.name}"
        print(command)
        run_cmd(command)
